---

- name: Reload and restart systemd service files
  systemd:
    name: conntrack-logging.service
    enabled: true
    state: restarted
    daemon_reload: true
  loop: [1, 2]
  loop_control:
    pause: 1
  listen: conntrack-logging-reload
